### ISSUE TITLE
About the data

### ISSUE THREAD

**Issue by yatru** [jishnair19/Covid19-Prediction#1]
Hi, could you please make the data available ?
Thanks

**Comment by jishnair19** [comment]
I have uploaded the dataset in my repository. Thanks for bringing it to my knowledge!

**Comment by yatru** [comment]
Thanks to you !!
Also, check the mexican open data website, you can get more data there

**Comment by jishnair19** [comment]
Thankyou brother, I will!

**Comment by yatru** [comment]
The most complete one I saw is this :

https://www.wolframcloud.com/obj/e2c7296d-54be-4c94-b055-c2d51316ecc1

Check it
